@startuml
hide methods
left to right direction

class Client {
    - Integer id
    - String name
    - String emailAddress
    - String password
    - String cellphone
    - Integer nif
    - Integer numberOfCredits
}

class Order {
    - Integer id
}


class Pharmacy {
    - Integer id
    - String designation
    - String nif
}


class Application {}


Application "1" -- "1..*" Pharmacy: has >
Pharmacy "1" -- "1..*" Order: has >
Pharmacy "1" -- "1..*" Order: make >
Application "1" -- "1..*" Client: has >
Client "1" -- "0..*" Order: make >

@enduml
