@startuml
autonumber
actor "Admin" as ADM
participant ":System" as STM
activate ADM
ADM-> STM :starts removing a Drone
activate STM
STM --> ADM :shows the list of all Drone in the Database
deactivate STM
ADM -> STM : introduces the id of the Drone he wants to remove
activate STM
STM --> ADM :asks for confirmation
deactivate STM
ADM -> STM : confirms
activate STM
STM --> ADM : notifies the Admin that the Drone has been removed
deactivate STM

deactivate ADM
@enduml
