@startuml
autonumber

actor "Client" as Client
participant ":UpdateCreditsUI" as UI
participant ":UpdateCreditsController" as CTRL
participant "Order" as ORD
participant "Credits" as CRE
participant "client:CLIENT" as CLI


activate Client
Client -> UI : choose the credits option.
activate UI
UI -> CTRL : updateCredits()
activate CTRL
CTRL -> ORD : client = getClient()
activate ORD
deactivate ORD
CTRL -> CRE : credits = calculateNumberOfCredits(order, client)
activate CRE
deactivate CRE
CTRL -> CLI : updateCredits(credits)
activate CLI
deactivate CLI

UI --> Client : calculates the number of credits and update them
deactivate UI

deactivate Client
@enduml
