
-----------------------------------------------
--DELETES--------------------------------------
-----------------------------------------------
DELETE FROM "User";
DELETE FROM PHARMACYADMINISTRATOR;
DELETE FROM CREDITS;
DELETE FROM DELIVERY;
DELETE FROM ORDERITEM;
DELETE FROM STOCKITEM;
DELETE FROM STOCK;
DELETE FROM ITEM;
DELETE FROM RECEIPT;
DELETE FROM "Order";
DELETE FROM CLIENT;
DELETE FROM DRONEPARK;
DELETE FROM SCOOTERPARK;
DELETE From SCOOTER;
DELETE FROM DRONE;
DELETE FROM CHARGINGSTATION;
DELETE FROM PARKSLOT;
DELETE FROM VEHICLE;
DELETE FROM PARK;
DELETE FROM LANDPATH;
DELETE FROM AERIALPATH;
DELETE FROM PATH;
DELETE FROM GEOLOCATION;
DELETE FROM CLIENT;
DELETE FROM COURIER;
DELETE FROM PHARMACY;
DELETE FROM ADDRESS;
-----------------------------------------------
-----------------------------------------------
-----------------------------------------------

